server:
  port: ${PORT:${SERVER_PORT:0}}

info:
  id: ${spring.application.name}

debug: true

ha:
  server_id: ${random.value}

eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

